[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[context.production]
  environment = { NEXT_PUBLIC_DEPLOY_CONTEXT = "production" }

[context.deploy-preview.environment]
  NEXT_PUBLIC_DEPLOY_CONTEXT = "deploy-preview"

[context.branch-deploy.environment]
  NEXT_PUBLIC_DEPLOY_CONTEXT = "branch-deploy"

[context.dev.environment]
  NEXT_PUBLIC_DEPLOY_CONTEXT = "dev"
